[project]
name = "mlmodel-converter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "coremltools>=8.2",
    "torch>=2.6.0",
    "transformers>=4.50.3",
]
